version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: "smt-mongo-dev"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017